/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignInImport } from './routes/sign-in'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as ForgotPasswordImport } from './routes/forgot-password'
import { Route as LabsquireImport } from './routes/_labsquire'
import { Route as IndexImport } from './routes/index'
import { Route as LabsquireUpdatePasswordImport } from './routes/_labsquire/update-password'
import { Route as LabsquireGetProfileImport } from './routes/_labsquire/get-profile'
import { Route as LabsquireUsersUserTableImport } from './routes/_labsquire/users/user-table'
import { Route as LabsquireUsersEditUserFormImport } from './routes/_labsquire/users/edit-user-form'
import { Route as LabsquireUsersAddUserImport } from './routes/_labsquire/users/add-user'
import { Route as LabsquireTasksGetTaskStatsImport } from './routes/_labsquire/tasks/get-task-stats'
import { Route as LabsquireTasksAddTasksImport } from './routes/_labsquire/tasks/add-tasks'
import { Route as LabsquireProjectsProjectTableImport } from './routes/_labsquire/projects/project-table'
import { Route as LabsquireProjectsGetSingleProjectAddProjectImport } from './routes/_labsquire/projects/get-single-project/add-project'
import { Route as LabsquireProjectsGetSingleProjectProjectIdIndexImport } from './routes/_labsquire/projects/get-single-project/$projectId/index'
import { Route as LabsquireProjectsGetMembersProjectIdIndex1Import } from './routes/_labsquire/projects/get-members/$projectId/index1'

// Create/Update Routes

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const ForgotPasswordRoute = ForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const LabsquireRoute = LabsquireImport.update({
  id: '/_labsquire',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LabsquireUpdatePasswordRoute = LabsquireUpdatePasswordImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => LabsquireRoute,
} as any)

const LabsquireGetProfileRoute = LabsquireGetProfileImport.update({
  id: '/get-profile',
  path: '/get-profile',
  getParentRoute: () => LabsquireRoute,
} as any)

const LabsquireUsersUserTableRoute = LabsquireUsersUserTableImport.update({
  id: '/users/user-table',
  path: '/users/user-table',
  getParentRoute: () => LabsquireRoute,
} as any)

const LabsquireUsersEditUserFormRoute = LabsquireUsersEditUserFormImport.update(
  {
    id: '/users/edit-user-form',
    path: '/users/edit-user-form',
    getParentRoute: () => LabsquireRoute,
  } as any,
)

const LabsquireUsersAddUserRoute = LabsquireUsersAddUserImport.update({
  id: '/users/add-user',
  path: '/users/add-user',
  getParentRoute: () => LabsquireRoute,
} as any)

const LabsquireTasksGetTaskStatsRoute = LabsquireTasksGetTaskStatsImport.update(
  {
    id: '/tasks/get-task-stats',
    path: '/tasks/get-task-stats',
    getParentRoute: () => LabsquireRoute,
  } as any,
)

const LabsquireTasksAddTasksRoute = LabsquireTasksAddTasksImport.update({
  id: '/tasks/add-tasks',
  path: '/tasks/add-tasks',
  getParentRoute: () => LabsquireRoute,
} as any)

const LabsquireProjectsProjectTableRoute =
  LabsquireProjectsProjectTableImport.update({
    id: '/projects/project-table',
    path: '/projects/project-table',
    getParentRoute: () => LabsquireRoute,
  } as any)

const LabsquireProjectsGetSingleProjectAddProjectRoute =
  LabsquireProjectsGetSingleProjectAddProjectImport.update({
    id: '/projects/get-single-project/add-project',
    path: '/projects/get-single-project/add-project',
    getParentRoute: () => LabsquireRoute,
  } as any)

const LabsquireProjectsGetSingleProjectProjectIdIndexRoute =
  LabsquireProjectsGetSingleProjectProjectIdIndexImport.update({
    id: '/projects/get-single-project/$projectId/',
    path: '/projects/get-single-project/$projectId/',
    getParentRoute: () => LabsquireRoute,
  } as any)

const LabsquireProjectsGetMembersProjectIdIndex1Route =
  LabsquireProjectsGetMembersProjectIdIndex1Import.update({
    id: '/projects/get-members/$projectId/index1',
    path: '/projects/get-members/$projectId/index1',
    getParentRoute: () => LabsquireRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_labsquire': {
      id: '/_labsquire'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LabsquireImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/_labsquire/get-profile': {
      id: '/_labsquire/get-profile'
      path: '/get-profile'
      fullPath: '/get-profile'
      preLoaderRoute: typeof LabsquireGetProfileImport
      parentRoute: typeof LabsquireImport
    }
    '/_labsquire/update-password': {
      id: '/_labsquire/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof LabsquireUpdatePasswordImport
      parentRoute: typeof LabsquireImport
    }
    '/_labsquire/projects/project-table': {
      id: '/_labsquire/projects/project-table'
      path: '/projects/project-table'
      fullPath: '/projects/project-table'
      preLoaderRoute: typeof LabsquireProjectsProjectTableImport
      parentRoute: typeof LabsquireImport
    }
    '/_labsquire/tasks/add-tasks': {
      id: '/_labsquire/tasks/add-tasks'
      path: '/tasks/add-tasks'
      fullPath: '/tasks/add-tasks'
      preLoaderRoute: typeof LabsquireTasksAddTasksImport
      parentRoute: typeof LabsquireImport
    }
    '/_labsquire/tasks/get-task-stats': {
      id: '/_labsquire/tasks/get-task-stats'
      path: '/tasks/get-task-stats'
      fullPath: '/tasks/get-task-stats'
      preLoaderRoute: typeof LabsquireTasksGetTaskStatsImport
      parentRoute: typeof LabsquireImport
    }
    '/_labsquire/users/add-user': {
      id: '/_labsquire/users/add-user'
      path: '/users/add-user'
      fullPath: '/users/add-user'
      preLoaderRoute: typeof LabsquireUsersAddUserImport
      parentRoute: typeof LabsquireImport
    }
    '/_labsquire/users/edit-user-form': {
      id: '/_labsquire/users/edit-user-form'
      path: '/users/edit-user-form'
      fullPath: '/users/edit-user-form'
      preLoaderRoute: typeof LabsquireUsersEditUserFormImport
      parentRoute: typeof LabsquireImport
    }
    '/_labsquire/users/user-table': {
      id: '/_labsquire/users/user-table'
      path: '/users/user-table'
      fullPath: '/users/user-table'
      preLoaderRoute: typeof LabsquireUsersUserTableImport
      parentRoute: typeof LabsquireImport
    }
    '/_labsquire/projects/get-single-project/add-project': {
      id: '/_labsquire/projects/get-single-project/add-project'
      path: '/projects/get-single-project/add-project'
      fullPath: '/projects/get-single-project/add-project'
      preLoaderRoute: typeof LabsquireProjectsGetSingleProjectAddProjectImport
      parentRoute: typeof LabsquireImport
    }
    '/_labsquire/projects/get-members/$projectId/index1': {
      id: '/_labsquire/projects/get-members/$projectId/index1'
      path: '/projects/get-members/$projectId/index1'
      fullPath: '/projects/get-members/$projectId/index1'
      preLoaderRoute: typeof LabsquireProjectsGetMembersProjectIdIndex1Import
      parentRoute: typeof LabsquireImport
    }
    '/_labsquire/projects/get-single-project/$projectId/': {
      id: '/_labsquire/projects/get-single-project/$projectId/'
      path: '/projects/get-single-project/$projectId'
      fullPath: '/projects/get-single-project/$projectId'
      preLoaderRoute: typeof LabsquireProjectsGetSingleProjectProjectIdIndexImport
      parentRoute: typeof LabsquireImport
    }
  }
}

// Create and export the route tree

interface LabsquireRouteChildren {
  LabsquireGetProfileRoute: typeof LabsquireGetProfileRoute
  LabsquireUpdatePasswordRoute: typeof LabsquireUpdatePasswordRoute
  LabsquireProjectsProjectTableRoute: typeof LabsquireProjectsProjectTableRoute
  LabsquireTasksAddTasksRoute: typeof LabsquireTasksAddTasksRoute
  LabsquireTasksGetTaskStatsRoute: typeof LabsquireTasksGetTaskStatsRoute
  LabsquireUsersAddUserRoute: typeof LabsquireUsersAddUserRoute
  LabsquireUsersEditUserFormRoute: typeof LabsquireUsersEditUserFormRoute
  LabsquireUsersUserTableRoute: typeof LabsquireUsersUserTableRoute
  LabsquireProjectsGetSingleProjectAddProjectRoute: typeof LabsquireProjectsGetSingleProjectAddProjectRoute
  LabsquireProjectsGetMembersProjectIdIndex1Route: typeof LabsquireProjectsGetMembersProjectIdIndex1Route
  LabsquireProjectsGetSingleProjectProjectIdIndexRoute: typeof LabsquireProjectsGetSingleProjectProjectIdIndexRoute
}

const LabsquireRouteChildren: LabsquireRouteChildren = {
  LabsquireGetProfileRoute: LabsquireGetProfileRoute,
  LabsquireUpdatePasswordRoute: LabsquireUpdatePasswordRoute,
  LabsquireProjectsProjectTableRoute: LabsquireProjectsProjectTableRoute,
  LabsquireTasksAddTasksRoute: LabsquireTasksAddTasksRoute,
  LabsquireTasksGetTaskStatsRoute: LabsquireTasksGetTaskStatsRoute,
  LabsquireUsersAddUserRoute: LabsquireUsersAddUserRoute,
  LabsquireUsersEditUserFormRoute: LabsquireUsersEditUserFormRoute,
  LabsquireUsersUserTableRoute: LabsquireUsersUserTableRoute,
  LabsquireProjectsGetSingleProjectAddProjectRoute:
    LabsquireProjectsGetSingleProjectAddProjectRoute,
  LabsquireProjectsGetMembersProjectIdIndex1Route:
    LabsquireProjectsGetMembersProjectIdIndex1Route,
  LabsquireProjectsGetSingleProjectProjectIdIndexRoute:
    LabsquireProjectsGetSingleProjectProjectIdIndexRoute,
}

const LabsquireRouteWithChildren = LabsquireRoute._addFileChildren(
  LabsquireRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LabsquireRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/get-profile': typeof LabsquireGetProfileRoute
  '/update-password': typeof LabsquireUpdatePasswordRoute
  '/projects/project-table': typeof LabsquireProjectsProjectTableRoute
  '/tasks/add-tasks': typeof LabsquireTasksAddTasksRoute
  '/tasks/get-task-stats': typeof LabsquireTasksGetTaskStatsRoute
  '/users/add-user': typeof LabsquireUsersAddUserRoute
  '/users/edit-user-form': typeof LabsquireUsersEditUserFormRoute
  '/users/user-table': typeof LabsquireUsersUserTableRoute
  '/projects/get-single-project/add-project': typeof LabsquireProjectsGetSingleProjectAddProjectRoute
  '/projects/get-members/$projectId/index1': typeof LabsquireProjectsGetMembersProjectIdIndex1Route
  '/projects/get-single-project/$projectId': typeof LabsquireProjectsGetSingleProjectProjectIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LabsquireRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/get-profile': typeof LabsquireGetProfileRoute
  '/update-password': typeof LabsquireUpdatePasswordRoute
  '/projects/project-table': typeof LabsquireProjectsProjectTableRoute
  '/tasks/add-tasks': typeof LabsquireTasksAddTasksRoute
  '/tasks/get-task-stats': typeof LabsquireTasksGetTaskStatsRoute
  '/users/add-user': typeof LabsquireUsersAddUserRoute
  '/users/edit-user-form': typeof LabsquireUsersEditUserFormRoute
  '/users/user-table': typeof LabsquireUsersUserTableRoute
  '/projects/get-single-project/add-project': typeof LabsquireProjectsGetSingleProjectAddProjectRoute
  '/projects/get-members/$projectId/index1': typeof LabsquireProjectsGetMembersProjectIdIndex1Route
  '/projects/get-single-project/$projectId': typeof LabsquireProjectsGetSingleProjectProjectIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_labsquire': typeof LabsquireRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/_labsquire/get-profile': typeof LabsquireGetProfileRoute
  '/_labsquire/update-password': typeof LabsquireUpdatePasswordRoute
  '/_labsquire/projects/project-table': typeof LabsquireProjectsProjectTableRoute
  '/_labsquire/tasks/add-tasks': typeof LabsquireTasksAddTasksRoute
  '/_labsquire/tasks/get-task-stats': typeof LabsquireTasksGetTaskStatsRoute
  '/_labsquire/users/add-user': typeof LabsquireUsersAddUserRoute
  '/_labsquire/users/edit-user-form': typeof LabsquireUsersEditUserFormRoute
  '/_labsquire/users/user-table': typeof LabsquireUsersUserTableRoute
  '/_labsquire/projects/get-single-project/add-project': typeof LabsquireProjectsGetSingleProjectAddProjectRoute
  '/_labsquire/projects/get-members/$projectId/index1': typeof LabsquireProjectsGetMembersProjectIdIndex1Route
  '/_labsquire/projects/get-single-project/$projectId/': typeof LabsquireProjectsGetSingleProjectProjectIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/get-profile'
    | '/update-password'
    | '/projects/project-table'
    | '/tasks/add-tasks'
    | '/tasks/get-task-stats'
    | '/users/add-user'
    | '/users/edit-user-form'
    | '/users/user-table'
    | '/projects/get-single-project/add-project'
    | '/projects/get-members/$projectId/index1'
    | '/projects/get-single-project/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/get-profile'
    | '/update-password'
    | '/projects/project-table'
    | '/tasks/add-tasks'
    | '/tasks/get-task-stats'
    | '/users/add-user'
    | '/users/edit-user-form'
    | '/users/user-table'
    | '/projects/get-single-project/add-project'
    | '/projects/get-members/$projectId/index1'
    | '/projects/get-single-project/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_labsquire'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/_labsquire/get-profile'
    | '/_labsquire/update-password'
    | '/_labsquire/projects/project-table'
    | '/_labsquire/tasks/add-tasks'
    | '/_labsquire/tasks/get-task-stats'
    | '/_labsquire/users/add-user'
    | '/_labsquire/users/edit-user-form'
    | '/_labsquire/users/user-table'
    | '/_labsquire/projects/get-single-project/add-project'
    | '/_labsquire/projects/get-members/$projectId/index1'
    | '/_labsquire/projects/get-single-project/$projectId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabsquireRoute: typeof LabsquireRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabsquireRoute: LabsquireRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_labsquire",
        "/forgot-password",
        "/reset-password",
        "/sign-in"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_labsquire": {
      "filePath": "_labsquire.tsx",
      "children": [
        "/_labsquire/get-profile",
        "/_labsquire/update-password",
        "/_labsquire/projects/project-table",
        "/_labsquire/tasks/add-tasks",
        "/_labsquire/tasks/get-task-stats",
        "/_labsquire/users/add-user",
        "/_labsquire/users/edit-user-form",
        "/_labsquire/users/user-table",
        "/_labsquire/projects/get-single-project/add-project",
        "/_labsquire/projects/get-members/$projectId/index1",
        "/_labsquire/projects/get-single-project/$projectId/"
      ]
    },
    "/forgot-password": {
      "filePath": "forgot-password.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/_labsquire/get-profile": {
      "filePath": "_labsquire/get-profile.tsx",
      "parent": "/_labsquire"
    },
    "/_labsquire/update-password": {
      "filePath": "_labsquire/update-password.tsx",
      "parent": "/_labsquire"
    },
    "/_labsquire/projects/project-table": {
      "filePath": "_labsquire/projects/project-table.tsx",
      "parent": "/_labsquire"
    },
    "/_labsquire/tasks/add-tasks": {
      "filePath": "_labsquire/tasks/add-tasks.tsx",
      "parent": "/_labsquire"
    },
    "/_labsquire/tasks/get-task-stats": {
      "filePath": "_labsquire/tasks/get-task-stats.tsx",
      "parent": "/_labsquire"
    },
    "/_labsquire/users/add-user": {
      "filePath": "_labsquire/users/add-user.tsx",
      "parent": "/_labsquire"
    },
    "/_labsquire/users/edit-user-form": {
      "filePath": "_labsquire/users/edit-user-form.tsx",
      "parent": "/_labsquire"
    },
    "/_labsquire/users/user-table": {
      "filePath": "_labsquire/users/user-table.tsx",
      "parent": "/_labsquire"
    },
    "/_labsquire/projects/get-single-project/add-project": {
      "filePath": "_labsquire/projects/get-single-project/add-project.tsx",
      "parent": "/_labsquire"
    },
    "/_labsquire/projects/get-members/$projectId/index1": {
      "filePath": "_labsquire/projects/get-members/$projectId/index1.tsx",
      "parent": "/_labsquire"
    },
    "/_labsquire/projects/get-single-project/$projectId/": {
      "filePath": "_labsquire/projects/get-single-project/$projectId/index.tsx",
      "parent": "/_labsquire"
    }
  }
}
ROUTE_MANIFEST_END */
